import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/app/components/footer';
import Header from '@/app/components/header';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Header />
        <main className={`${inter.className} mx-40 min-h-screen`}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
